### ISSUE TITLE
Infografía Und.1

### ISSUE THREAD

**Issue by Danae953** [SistemasTecTlaxiaco/infografia-Danae953#1]
Infografía sobre la realidad aumentada y la realidad virtual
![Realidad aumentada](https://user-images.githubusercontent.com/67284534/110061186-c3168c80-7d2c-11eb-8602-144c7a5b5a29.jpg)
.

**Comment by ObedG** [comment]
Calificación: 19

**Comment by josealfredo79** [comment]
Esta bien hecho y revisado
